#include <iostream>
#include "player.h"
#include "casino.h"


int main()
{
	/*
	
	The player needs to guess a random number generated by the computer.
	If the player guesses right, they will win a certain amount of money.
	The winning prize depends on the difficulty of the game. 
	

	Classes:
	- Player (name, amount of money, setMoney, (maybe) adjustMoney)
	- Game (difficulty, game logic, stake, possible reward, randomness)

	*/

	Player test;

	game(test, getDifficulty());

	return 0;
}